/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 ntree.gltf --transform
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function NTree(props) {
  const { nodes, materials } = useGLTF('/ntree-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <group rotation={[Math.PI / 2, 0, 0]}>
        <mesh geometry={nodes.Tree_1.geometry} material={materials.KPOHA} />
        <mesh geometry={nodes.Tree_2.geometry} material={materials.CTBOL} />
        <mesh geometry={nodes.Tree_3.geometry} material={materials.Ground_and_rock} />
        <mesh geometry={nodes.Tree_4.geometry} material={materials.Grass} />
        <mesh geometry={nodes.Tree_5.geometry} material={materials.LISTBA} />
      </group>
    </group>
  )
}

useGLTF.preload('/ntree-transformed.glb')
