/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 piggy.gltf --transform
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Pig(props) {
  const { nodes, materials } = useGLTF('/piggy-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Plane.geometry} material={materials['default']} position={[0, 0, -2.2]} scale={3.72} />
      <mesh geometry={nodes.Cube_1.geometry} material={materials.Material} />
      <mesh geometry={nodes.Cube_2.geometry} material={materials['Material.001']} />
    </group>
  )
}

useGLTF.preload('/piggy-transformed.glb')
