/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 recycling.gltf --transform
Author: emijar (https://sketchfab.com/emijar)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/recycling-bins-43581281d5034abbb1ca9b686267015d
Title: Recycling Bins
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function RecyclingBins(props) {
  const { nodes, materials } = useGLTF('/recycling-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.polySurface13_blinn5_0.geometry} material={materials.blinn5} />
      <mesh geometry={nodes.polySurface13_bin1_0.geometry} material={materials.bin1} />
      <mesh geometry={nodes.polySurface13_blinn2_0.geometry} material={materials.blinn2} />
      <mesh geometry={nodes.polySurface13_restmull_0.geometry} material={materials.restmull} />
      <mesh geometry={nodes.polySurface13_glas_0.geometry} material={materials.glas} />
      <mesh geometry={nodes.polySurface13_papier_0.geometry} material={materials.papier} />
      <mesh geometry={nodes.polySurface13_verpackung_0.geometry} material={materials.verpackung} />
      <mesh geometry={nodes.polySurface13_blinn4_0.geometry} material={materials.blinn4} />
      <mesh geometry={nodes.polySurface13_blinn1_0.geometry} material={materials.blinn1} />
      <mesh geometry={nodes.polySurface13_blinn3_0.geometry} material={materials.blinn3} />
    </group>
  )
}

useGLTF.preload('/recycling-transformed.glb')
