/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 water.gltf --transform
Author: furret (https://sketchfab.com/ff.ferretti02)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/drop-of-water-dcbdc5e8905449ad95a47720e4d3c57c
Title: drop of water
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Water(props) {
  const { nodes, materials } = useGLTF('/water-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Object_4.geometry} material={materials.Material} position={[1.87, 1.23, -1.21]} />
      <mesh geometry={nodes.Object_6.geometry} material={materials.Material} position={[0.56, 2.67, -0.8]} scale={0.39} />
      <mesh geometry={nodes.Object_8.geometry} material={materials.Material} position={[0.66, 2.22, -1.66]} scale={0.26} />
    </group>
  )
}

useGLTF.preload('/water-transformed.glb')
