/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 beach.gltf --transform
Author: Belzar Sirus (https://sketchfab.com/belzar.sirus)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/sea-shack-c2b71ae9c18f45ef88828c2022c40918
Title: Sea Shack
*/

import React, { useRef } from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'

export default function Model(props) {
  const group = useRef()
  const { nodes, materials, animations } = useGLTF('/beach-transformed.glb')
  const { actions } = useAnimations(animations, group)
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Sketchfab_Scene">
        <group name="Sketchfab_model" rotation={[-Math.PI / 2, 0, 0]}>
          <group name="root">
            <group name="GLTF_SceneRootNode" rotation={[Math.PI / 2, 0, 0]}>
              <group name="Fish_1001_42" position={[-3.4, 10.76, 6.48]} rotation={[0.9, -1.49, 0.89]} scale={0.37}>
                <group name="GLTF_created_2">
                  <primitive object={nodes.GLTF_created_2_rootJoint} />
                  <skinnedMesh name="Object_69" geometry={nodes.Object_69.geometry} material={materials.Fish_1} skeleton={nodes.Object_69.skeleton} />
                  <skinnedMesh name="Object_70" geometry={nodes.Object_70.geometry} material={materials['Fish_1_eye.02']} skeleton={nodes.Object_70.skeleton} />
                  <skinnedMesh name="Object_71" geometry={nodes.Object_71.geometry} material={materials['Fish_1_eye.03']} skeleton={nodes.Object_71.skeleton} />
                  <skinnedMesh name="Object_72" geometry={nodes.Object_72.geometry} material={materials['Fish_1.001']} skeleton={nodes.Object_72.skeleton} />
                </group>
              </group>
              <group name="Empty_44" position={[-4.25, 11.18, 6.13]} rotation={[2.85, -1.18, 2.87]} />
              <group name="Fish_1002_51" position={[-3.4, 10.76, 6.48]} rotation={[0.9, -1.49, 0.89]} scale={0.37}>
                <group name="GLTF_created_3">
                  <primitive object={nodes.GLTF_created_3_rootJoint} />
                  <skinnedMesh name="Object_83" geometry={nodes.Object_83.geometry} material={materials.Fish_1} skeleton={nodes.Object_83.skeleton} />
                  <skinnedMesh name="Object_84" geometry={nodes.Object_84.geometry} material={materials['Fish_1_eye.02']} skeleton={nodes.Object_84.skeleton} />
                  <skinnedMesh name="Object_86" geometry={nodes.Object_86.geometry} material={materials['Fish_1.001']} skeleton={nodes.Object_86.skeleton} />
                  <skinnedMesh name="Object_85" geometry={nodes.Object_85.geometry} material={materials['Fish_1_eye.03']} skeleton={nodes.Object_85.skeleton} />
                </group>
              </group>
              <group name="Empty001_52" position={[-3.4, 10.76, 6.48]} rotation={[0.9, -1.49, 0.89]} scale={0.37} />
              <group name="Fish_1003_80" position={[-2.72, 10.84, 6.09]} rotation={[-0.3, -0.91, -0.25]} scale={0.3}>
                <group name="GLTF_created_6">
                  <primitive object={nodes.GLTF_created_6_rootJoint} />
                  <skinnedMesh name="Object_128" geometry={nodes.Object_128.geometry} material={materials.Fish_1} skeleton={nodes.Object_128.skeleton} />
                  <skinnedMesh name="Object_129" geometry={nodes.Object_129.geometry} material={materials['Fish_1_eye.02']} skeleton={nodes.Object_129.skeleton} />
                  <skinnedMesh name="Object_130" geometry={nodes.Object_130.geometry} material={materials['Fish_1_eye.03']} skeleton={nodes.Object_130.skeleton} />
                  <skinnedMesh name="Object_131" geometry={nodes.Object_131.geometry} material={materials['Fish_1.001']} skeleton={nodes.Object_131.skeleton} />
                </group>
              </group>
              <group name="Empty002_81" position={[-2.72, 10.84, 6.09]} rotation={[-0.3, -0.91, -0.25]} scale={0.3} />
              <group name="Fish_1004_90" position={[-2.29, 10.78, -4.03]} rotation={[0.13, -1.03, 0.13]} scale={0.24}>
                <group name="GLTF_created_7">
                  <primitive object={nodes.GLTF_created_7_rootJoint} />
                  <skinnedMesh name="Object_142" geometry={nodes.Object_142.geometry} material={materials.Fish_1} skeleton={nodes.Object_142.skeleton} />
                  <skinnedMesh name="Object_143" geometry={nodes.Object_143.geometry} material={materials['Fish_1_eye.02']} skeleton={nodes.Object_143.skeleton} />
                  <skinnedMesh name="Object_144" geometry={nodes.Object_144.geometry} material={materials['Fish_1_eye.03']} skeleton={nodes.Object_144.skeleton} />
                  <skinnedMesh name="Object_145" geometry={nodes.Object_145.geometry} material={materials['Fish_1.001']} skeleton={nodes.Object_145.skeleton} />
                </group>
              </group>
              <group name="Empty003_91" position={[-2.29, 10.78, -4.03]} rotation={[0.13, -1.03, 0.13]} scale={0.24} />
              <group name="Fish_1005_99" position={[-2.26, 10.95, -4]} rotation={[0.12, -1.03, 0.11]} scale={0.12}>
                <group name="GLTF_created_8">
                  <primitive object={nodes.GLTF_created_8_rootJoint} />
                  <skinnedMesh name="Object_156" geometry={nodes.Object_156.geometry} material={materials.Fish_1} skeleton={nodes.Object_156.skeleton} />
                  <skinnedMesh name="Object_157" geometry={nodes.Object_157.geometry} material={materials['Fish_1_eye.02']} skeleton={nodes.Object_157.skeleton} />
                  <skinnedMesh name="Object_158" geometry={nodes.Object_158.geometry} material={materials['Fish_1_eye.03']} skeleton={nodes.Object_158.skeleton} />
                  <skinnedMesh name="Object_159" geometry={nodes.Object_159.geometry} material={materials['Fish_1.001']} skeleton={nodes.Object_159.skeleton} />
                </group>
              </group>
              <group name="Empty004_100" position={[-2.26, 10.95, -4]} rotation={[0.12, -1.03, 0.11]} scale={0.12} />
              <group name="Fish_1006_108" position={[-2.2, 10.95, -4.18]} rotation={[0.13, -1.03, 0.13]} scale={0.23}>
                <group name="GLTF_created_9">
                  <primitive object={nodes.GLTF_created_9_rootJoint} />
                  <skinnedMesh name="Object_170" geometry={nodes.Object_170.geometry} material={materials.Fish_1} skeleton={nodes.Object_170.skeleton} />
                  <skinnedMesh name="Object_171" geometry={nodes.Object_171.geometry} material={materials['Fish_1_eye.02']} skeleton={nodes.Object_171.skeleton} />
                  <skinnedMesh name="Object_172" geometry={nodes.Object_172.geometry} material={materials['Fish_1_eye.03']} skeleton={nodes.Object_172.skeleton} />
                  <skinnedMesh name="Object_173" geometry={nodes.Object_173.geometry} material={materials['Fish_1.001']} skeleton={nodes.Object_173.skeleton} />
                </group>
              </group>
              <group name="Empty005_109" position={[-2.2, 10.95, -4.18]} rotation={[0.13, -1.03, 0.13]} scale={0.23} />
              <group name="Fish_1007_117" position={[-2.22, 10.76, -4.22]} rotation={[0.12, -1.04, 0.12]} scale={0.31}>
                <group name="GLTF_created_10">
                  <primitive object={nodes.GLTF_created_10_rootJoint} />
                  <skinnedMesh name="Object_184" geometry={nodes.Object_184.geometry} material={materials.Fish_1} skeleton={nodes.Object_184.skeleton} />
                  <skinnedMesh name="Object_185" geometry={nodes.Object_185.geometry} material={materials['Fish_1_eye.02']} skeleton={nodes.Object_185.skeleton} />
                  <skinnedMesh name="Object_186" geometry={nodes.Object_186.geometry} material={materials['Fish_1_eye.03']} skeleton={nodes.Object_186.skeleton} />
                  <skinnedMesh name="Object_187" geometry={nodes.Object_187.geometry} material={materials['Fish_1.001']} skeleton={nodes.Object_187.skeleton} />
                </group>
              </group>
              <group name="Empty006_118" position={[-2.22, 10.76, -4.22]} rotation={[0.12, -1.04, 0.12]} scale={0.31} />
              <group name="Fish_1008_126" position={[-2.27, 10.84, -4.1]} rotation={[0.12, -1.04, 0.12]} scale={0.2}>
                <group name="GLTF_created_11">
                  <primitive object={nodes.GLTF_created_11_rootJoint} />
                  <skinnedMesh name="Object_198" geometry={nodes.Object_198.geometry} material={materials.Fish_1} skeleton={nodes.Object_198.skeleton} />
                  <skinnedMesh name="Object_199" geometry={nodes.Object_199.geometry} material={materials['Fish_1_eye.02']} skeleton={nodes.Object_199.skeleton} />
                  <skinnedMesh name="Object_200" geometry={nodes.Object_200.geometry} material={materials['Fish_1_eye.03']} skeleton={nodes.Object_200.skeleton} />
                  <skinnedMesh name="Object_201" geometry={nodes.Object_201.geometry} material={materials['Fish_1.001']} skeleton={nodes.Object_201.skeleton} />
                </group>
              </group>
              <group name="Empty007_127" position={[-2.27, 10.84, -4.1]} rotation={[0.12, -1.04, 0.12]} scale={0.2} />
              <group name="Armature002_138" position={[5.86, 11.1, -5.4]} rotation={[-3.01, 0.88, 3.04]}>
                <group name="GLTF_created_12">
                  <primitive object={nodes.GLTF_created_12_rootJoint} />
                  <skinnedMesh name="Object_212" geometry={nodes.Object_212.geometry} material={materials.LightFish_base} skeleton={nodes.Object_212.skeleton} />
                  <skinnedMesh name="Object_213" geometry={nodes.Object_213.geometry} material={materials.LightFish_Teeth} skeleton={nodes.Object_213.skeleton} />
                  <skinnedMesh name="Object_214" geometry={nodes.Object_214.geometry} material={materials['Fish_1_eye.02']} skeleton={nodes.Object_214.skeleton} />
                  <skinnedMesh name="Object_215" geometry={nodes.Object_215.geometry} material={materials['Fish_1_eye.03']} skeleton={nodes.Object_215.skeleton} />
                  <skinnedMesh name="Object_216" geometry={nodes.Object_216.geometry} material={materials.LightFish_Light} skeleton={nodes.Object_216.skeleton} />
                  <skinnedMesh name="Object_217" geometry={nodes.Object_217.geometry} material={materials.LightFish_Mouth} skeleton={nodes.Object_217.skeleton} />
                </group>
              </group>
              <group name="Empty008_140" position={[5.86, 11.1, -5.4]} rotation={[-3.01, 0.88, 3.04]} />
              <group name="Fish_1009_322" position={[-4.24, 11.19, 6.13]} rotation={[2.92, -1.27, 2.91]} scale={0.68}>
                <group name="GLTF_created_26">
                  <primitive object={nodes.GLTF_created_26_rootJoint} />
                  <skinnedMesh name="Object_448" geometry={nodes.Object_448.geometry} material={materials.Fish_1} skeleton={nodes.Object_448.skeleton} />
                  <skinnedMesh name="Object_449" geometry={nodes.Object_449.geometry} material={materials['Fish_1_eye.02']} skeleton={nodes.Object_449.skeleton} />
                  <skinnedMesh name="Object_450" geometry={nodes.Object_450.geometry} material={materials['Fish_1_eye.03']} skeleton={nodes.Object_450.skeleton} />
                  <skinnedMesh name="Object_451" geometry={nodes.Object_451.geometry} material={materials['Fish_1.001']} skeleton={nodes.Object_451.skeleton} />
                </group>
                          </group>
              {/*WATER*/}
              <group name="Armature_5" position={[2.7, 12.98, 1.5]}>
                <group name="GLTF_created_0">
                  <primitive object={nodes.GLTF_created_0_rootJoint} />
                                  <skinnedMesh name="Object_7" geometry={nodes.Object_7.geometry} material={materials.Watter} skeleton={nodes.Object_7.skeleton} />
                                  <color attach="background" args={["#8fce00"]} />

                </group>
              </group>
              <group name="Plank_Smal_2007_6" position={[2.92, 20.46, 1.94]} rotation={[-Math.PI / 2, 0, 0]} scale={0.2}>
                <mesh name="Object_13" geometry={nodes.Object_13.geometry} material={materials.Wood_2} />
              </group>
              <group name="Plank_Smal_2009_7" position={[2.46, 20.64, 1.94]} rotation={[Math.PI / 2, 0, -Math.PI]} scale={0.2}>
                <mesh name="Object_15" geometry={nodes.Object_15.geometry} material={materials.Wood_1} />
              </group>
              <group name="Plank_3005_8" position={[1.98, 21.08, 1.94]} rotation={[Math.PI / 2, 0, 0]} scale={0.2}>
                <mesh name="Object_17" geometry={nodes.Object_17.geometry} material={materials.Wood_2} />
              </group>
              <group name="Plank_3007_9" position={[1.66, 20.22, 1.94]} rotation={[-Math.PI / 2, 0, -Math.PI]} scale={0.2}>
                <mesh name="Object_19" geometry={nodes.Object_19.geometry} material={materials.Wood_1} />
              </group>
              <group name="Plank_2010_10" position={[1.26, 19.13, 1.54]} rotation={[Math.PI / 2, 0, -Math.PI / 2]} scale={0.2}>
                <mesh name="Object_21" geometry={nodes.Object_21.geometry} material={materials.Wood_1} />
              </group>
              <group name="Plank_Smal_2010_11" position={[1.26, 20.98, 1.53]} rotation={[-Math.PI / 2, 0, Math.PI / 2]} scale={0.2}>
                <mesh name="Object_23" geometry={nodes.Object_23.geometry} material={materials.Wood_2} />
              </group>
              <group name="Plank_2011_12" position={[3.33, 19.11, 1.57]} rotation={[Math.PI / 2, 0, -Math.PI / 2]} scale={0.2}>
                <mesh name="Object_25" geometry={nodes.Object_25.geometry} material={materials.Wood_1} />
              </group>
              <group name="Plank_2012_13" position={[3.31, 19.11, 1.09]} rotation={[-Math.PI / 2, 0, Math.PI / 2]} scale={0.2}>
                <mesh name="Object_27" geometry={nodes.Object_27.geometry} material={materials.Wood_2} />
              </group>
              <group name="Plank_3006_14" position={[3.34, 19.17, 0.65]} rotation={[1.57, 0, Math.PI / 2]} scale={0.2}>
                <mesh name="Object_29" geometry={nodes.Object_29.geometry} material={materials.Wood_1} />
              </group>
              <group name="Plank_Smal_2011_15" position={[2.92, 20.46, 0.19]} rotation={[-Math.PI / 2, 0, 0]} scale={0.2}>
                <mesh name="Object_31" geometry={nodes.Object_31.geometry} material={materials.Wood_1} />
              </group>
              <group name="Plank_Smal_2012_16" position={[2.46, 20.64, 0.19]} rotation={[Math.PI / 2, 0, -Math.PI]} scale={0.2}>
                <mesh name="Object_33" geometry={nodes.Object_33.geometry} material={materials.Wood_2} />
              </group>
              <group name="Plank_3008_17" position={[1.98, 21.08, 0.19]} rotation={[Math.PI / 2, 0, 0]} scale={0.2}>
                <mesh name="Object_35" geometry={nodes.Object_35.geometry} material={materials.Wood_1} />
              </group>
              <group name="Plank_3009_18" position={[1.66, 20.22, 0.19]} rotation={[-Math.PI / 2, 0, -Math.PI]} scale={0.2}>
                <mesh name="Object_37" geometry={nodes.Object_37.geometry} material={materials.Wood_1} />
              </group>
              <group name="Plank_2013_19" position={[1.26, 19.15, 0.98]} rotation={[Math.PI / 2, 0, Math.PI / 2]} scale={0.2}>
                <mesh name="Object_39" geometry={nodes.Object_39.geometry} material={materials.Wood_2} />
              </group>
              <group name="Plank_Smal_2013_20" position={[1.26, 20.99, 0.99]} rotation={[-Math.PI / 2, 0, -Math.PI / 2]} scale={0.2}>
                <mesh name="Object_41" geometry={nodes.Object_41.geometry} material={materials.Wood_1} />
              </group>
              <group name="Plank_3010_21" position={[1.25, 20.24, 0.56]} rotation={[-Math.PI / 2, 0, Math.PI / 2]} scale={0.2}>
                <mesh name="Object_43" geometry={nodes.Object_43.geometry} material={materials.Wood_1} />
              </group>
              <group name="Armature_SeaGull_35" position={[1.06, 18.67, 3.57]}>
                <group name="GLTF_created_1">
                  <primitive object={nodes.GLTF_created_1_rootJoint} />
                  <skinnedMesh name="Object_48" geometry={nodes.Object_48.geometry} material={materials.Sea_Gull_Base} skeleton={nodes.Object_48.skeleton} />
                  <skinnedMesh name="Object_49" geometry={nodes.Object_49.geometry} material={materials.Sea_Gull_Dark} skeleton={nodes.Object_49.skeleton} />
                  <skinnedMesh name="Object_50" geometry={nodes.Object_50.geometry} material={materials.Sea_Gull_Beak} skeleton={nodes.Object_50.skeleton} />
                  <skinnedMesh name="Object_51" geometry={nodes.Object_51.geometry} material={materials.Sea_Gull_Eye} skeleton={nodes.Object_51.skeleton} />
                  <skinnedMesh name="Object_52" geometry={nodes.Object_52.geometry} material={materials.Sea_Gull_Feet} skeleton={nodes.Object_52.skeleton} />
                </group>
              </group>
              <group name="Armature_SeaGull001_66" position={[7.31, 13.64, 5.97]} rotation={[-Math.PI, 0.71, -Math.PI]} scale={1.28}>
                <group name="GLTF_created_4">
                  <primitive object={nodes.GLTF_created_4_rootJoint} />
                  <skinnedMesh name="Object_97" geometry={nodes.Object_97.geometry} material={materials.Sea_Gull_Base} skeleton={nodes.Object_97.skeleton} />
                  <skinnedMesh name="Object_98" geometry={nodes.Object_98.geometry} material={materials.Sea_Gull_Dark} skeleton={nodes.Object_98.skeleton} />
                  <skinnedMesh name="Object_99" geometry={nodes.Object_99.geometry} material={materials.Sea_Gull_Beak} skeleton={nodes.Object_99.skeleton} />
                  <skinnedMesh name="Object_100" geometry={nodes.Object_100.geometry} material={materials.Sea_Gull_Eye} skeleton={nodes.Object_100.skeleton} />
                  <skinnedMesh name="Object_101" geometry={nodes.Object_101.geometry} material={materials.Sea_Gull_Feet} skeleton={nodes.Object_101.skeleton} />
                </group>
              </group>
              <group name="Armature001_72" position={[5.04, 22.13, 1.73]}>
                <group name="GLTF_created_5">
                  <primitive object={nodes.GLTF_created_5_rootJoint} />
                  <skinnedMesh name="Object_118" geometry={nodes.Object_118.geometry} material={materials.Flag_Base} skeleton={nodes.Object_118.skeleton} />
                  <skinnedMesh name="Object_119" geometry={nodes.Object_119.geometry} material={materials.Flag_Color} skeleton={nodes.Object_119.skeleton} />
                </group>
              </group>
              <group name="Armature023_154" position={[9.14, 9.67, -4.6]}>
                <group name="GLTF_created_13">
                  <primitive object={nodes.GLTF_created_13_rootJoint} />
                  <skinnedMesh name="Object_231" geometry={nodes.Object_231.geometry} material={materials.SeaWeed_1} skeleton={nodes.Object_231.skeleton} />
                </group>
              </group>
              <group name="Armature024_168" position={[9.32, 9.67, -3.94]} rotation={[-Math.PI, 0.11, -Math.PI]} scale={0.58}>
                <group name="GLTF_created_14">
                  <primitive object={nodes.GLTF_created_14_rootJoint} />
                  <skinnedMesh name="Object_248" geometry={nodes.Object_248.geometry} material={materials.SeaWeed_1} skeleton={nodes.Object_248.skeleton} />
                </group>
              </group>
              <group name="Armature025_182" position={[7.56, 9.67, 0.69]} rotation={[-Math.PI, -0.78, -Math.PI]} scale={1.52}>
                <group name="GLTF_created_15">
                  <primitive object={nodes.GLTF_created_15_rootJoint} />
                  <skinnedMesh name="Object_265" geometry={nodes.Object_265.geometry} material={materials.SeaWeed_1} skeleton={nodes.Object_265.skeleton} />
                </group>
              </group>
              <group name="Armature026_196" position={[10.43, 9.67, -0.86]} rotation={[-Math.PI, 0.87, -Math.PI]} scale={0.58}>
                <group name="GLTF_created_16">
                  <primitive object={nodes.GLTF_created_16_rootJoint} />
                  <skinnedMesh name="Object_282" geometry={nodes.Object_282.geometry} material={materials.SeaWeed_1} skeleton={nodes.Object_282.skeleton} />
                </group>
              </group>
              <group name="Armature027_210" position={[10.76, 9.67, -0.55]} rotation={[0, 0.52, 0]} scale={0.42}>
                <group name="GLTF_created_17">
                  <primitive object={nodes.GLTF_created_17_rootJoint} />
                  <skinnedMesh name="Object_299" geometry={nodes.Object_299.geometry} material={materials.SeaWeed_1} skeleton={nodes.Object_299.skeleton} />
                </group>
              </group>
              <group name="Armature021_224" position={[-4.27, 9.67, 8.48]} rotation={[0, 1.49, 0]} scale={0.98}>
                <group name="GLTF_created_18">
                  <primitive object={nodes.GLTF_created_18_rootJoint} />
                  <skinnedMesh name="Object_316" geometry={nodes.Object_316.geometry} material={materials.SeaWeed_1} skeleton={nodes.Object_316.skeleton} />
                </group>
              </group>
              <group name="Armature028_238" position={[-3.93, 9.67, 8.18]} rotation={[-Math.PI, -0.4, -Math.PI]} scale={1.2}>
                <group name="GLTF_created_19">
                  <primitive object={nodes.GLTF_created_19_rootJoint} />
                  <skinnedMesh name="Object_333" geometry={nodes.Object_333.geometry} material={materials.SeaWeed_1} skeleton={nodes.Object_333.skeleton} />
                </group>
              </group>
              <group name="Armature029_252" position={[-3.23, 9.67, 8.68]} rotation={[0, -1.47, 0]} scale={0.68}>
                <group name="GLTF_created_20">
                  <primitive object={nodes.GLTF_created_20_rootJoint} />
                  <skinnedMesh name="Object_350" geometry={nodes.Object_350.geometry} material={materials.SeaWeed_1} skeleton={nodes.Object_350.skeleton} />
                </group>
              </group>
              <group name="Armature030_266" position={[-1.96, 9.67, -3.29]} rotation={[-Math.PI, -0.4, -Math.PI]} scale={1.05}>
                <group name="GLTF_created_21">
                  <primitive object={nodes.GLTF_created_21_rootJoint} />
                  <skinnedMesh name="Object_367" geometry={nodes.Object_367.geometry} material={materials.SeaWeed_1} skeleton={nodes.Object_367.skeleton} />
                </group>
              </group>
              <group name="Armature031_280" position={[-1.38, 9.67, -3.12]} rotation={[0, -0.81, 0]} scale={0.73}>
                <group name="GLTF_created_22">
                  <primitive object={nodes.GLTF_created_22_rootJoint} />
                  <skinnedMesh name="Object_384" geometry={nodes.Object_384.geometry} material={materials.SeaWeed_1} skeleton={nodes.Object_384.skeleton} />
                </group>
              </group>
              <group name="Armature032_294" position={[-1.4, 9.67, -3.97]} rotation={[0, 1.37, 0]} scale={0.73}>
                <group name="GLTF_created_23">
                  <primitive object={nodes.GLTF_created_23_rootJoint} />
                  <skinnedMesh name="Object_401" geometry={nodes.Object_401.geometry} material={materials.SeaWeed_1} skeleton={nodes.Object_401.skeleton} />
                </group>
              </group>
              <group name="Armature033_308" position={[-0.94, 9.67, -3.6]} rotation={[-Math.PI, -0.87, -Math.PI]} scale={0.53}>
                <group name="GLTF_created_24">
                  <primitive object={nodes.GLTF_created_24_rootJoint} />
                  <skinnedMesh name="Object_418" geometry={nodes.Object_418.geometry} material={materials.SeaWeed_1} skeleton={nodes.Object_418.skeleton} />
                </group>
              </group>
              <group name="Armature034_315" position={[4.37, 13.4, 6.29]} rotation={[0, -0.26, 0]}>
                <group name="GLTF_created_25">
                  <primitive object={nodes.GLTF_created_25_rootJoint} />
                  <skinnedMesh name="Object_435" geometry={nodes.Object_435.geometry} material={materials.Wood_4} skeleton={nodes.Object_435.skeleton} />
                  <skinnedMesh name="Object_436" geometry={nodes.Object_436.geometry} material={materials.Rope} skeleton={nodes.Object_436.skeleton} />
                  <skinnedMesh name="Object_437" geometry={nodes.Object_437.geometry} material={materials.Wood_Dark} skeleton={nodes.Object_437.skeleton} />
                  <skinnedMesh name="Object_438" geometry={nodes.Object_438.geometry} material={materials.Wood_1} skeleton={nodes.Object_438.skeleton} />
                </group>
              </group>
              <group name="Armature003_336" position={[1.04, 9.67, 7.72]} rotation={[0, 1.49, 0]} scale={0.82}>
                <group name="GLTF_created_27">
                  <primitive object={nodes.GLTF_created_27_rootJoint} />
                  <skinnedMesh name="Object_461" geometry={nodes.Object_461.geometry} material={materials.SeaWeed_1} skeleton={nodes.Object_461.skeleton} />
                </group>
              </group>
              <group name="Armature004_350" position={[8.54, 9.67, 9.02]} rotation={[0, 1.49, 0]} scale={1.16}>
                <group name="GLTF_created_28">
                  <primitive object={nodes.GLTF_created_28_rootJoint} />
                  <skinnedMesh name="Object_478" geometry={nodes.Object_478.geometry} material={materials.SeaWeed_1} skeleton={nodes.Object_478.skeleton} />
                </group>
              </group>
              <group name="Armature005_364" position={[8.52, 9.67, 8.39]} rotation={[-Math.PI, 0.45, -Math.PI]} scale={0.73}>
                <group name="GLTF_created_29">
                  <primitive object={nodes.GLTF_created_29_rootJoint} />
                  <skinnedMesh name="Object_495" geometry={nodes.Object_495.geometry} material={materials.SeaWeed_1} skeleton={nodes.Object_495.skeleton} />
                </group>
              </group>
              <group name="Armature006_378" position={[9.39, 9.67, 7.36]} rotation={[0, -0.28, 0]} scale={1.5}>
                <group name="GLTF_created_30">
                  <primitive object={nodes.GLTF_created_30_rootJoint} />
                  <skinnedMesh name="Object_512" geometry={nodes.Object_512.geometry} material={materials.SeaWeed_1} skeleton={nodes.Object_512.skeleton} />
                </group>
              </group>
              <group name="Armature007_392" position={[10.01, 9.67, 7.46]} rotation={[0, -0.26, 0]} scale={0.57}>
                <group name="GLTF_created_31">
                  <primitive object={nodes.GLTF_created_31_rootJoint} />
                  <skinnedMesh name="Object_529" geometry={nodes.Object_529.geometry} material={materials.SeaWeed_1} skeleton={nodes.Object_529.skeleton} />
                </group>
              </group>
              <group name="Armature008_406" position={[9.12, 9.67, 1.15]} rotation={[0, 0.74, 0]} scale={0.73}>
                <group name="GLTF_created_32">
                  <primitive object={nodes.GLTF_created_32_rootJoint} />
                  <skinnedMesh name="Object_546" geometry={nodes.Object_546.geometry} material={materials.SeaWeed_1} skeleton={nodes.Object_546.skeleton} />
                </group>
              </group>
              <group name="Armature009_420" position={[9.74, 9.67, 2.35]} rotation={[Math.PI, -0.9, Math.PI]} scale={1.5}>
                <group name="GLTF_created_33">
                  <primitive object={nodes.GLTF_created_33_rootJoint} />
                  <skinnedMesh name="Object_563" geometry={nodes.Object_563.geometry} material={materials.SeaWeed_1} skeleton={nodes.Object_563.skeleton} />
                </group>
              </group>
              <group name="Armature010_434" position={[9.41, 9.67, 2.88]} rotation={[Math.PI, -0.93, Math.PI]} scale={0.57}>
                <group name="GLTF_created_34">
                  <primitive object={nodes.GLTF_created_34_rootJoint} />
                  <skinnedMesh name="Object_580" geometry={nodes.Object_580.geometry} material={materials.SeaWeed_1} skeleton={nodes.Object_580.skeleton} />
                </group>
              </group>
              <group name="Armature011_448" position={[5.65, 9.67, -5.03]} rotation={[0, 0.74, 0]} scale={0.73}>
                <group name="GLTF_created_35">
                  <primitive object={nodes.GLTF_created_35_rootJoint} />
                  <skinnedMesh name="Object_597" geometry={nodes.Object_597.geometry} material={materials.SeaWeed_1} skeleton={nodes.Object_597.skeleton} />
                </group>
              </group>
              <group name="Armature012_462" position={[6.57, 9.67, -4.5]} rotation={[0, 0.09, 0]} scale={1.61}>
                <group name="GLTF_created_36">
                  <primitive object={nodes.GLTF_created_36_rootJoint} />
                  <skinnedMesh name="Object_614" geometry={nodes.Object_614.geometry} material={materials.SeaWeed_1} skeleton={nodes.Object_614.skeleton} />
                </group>
              </group>
              <group name="Armature013_476" position={[5.94, 9.67, -3.3]} rotation={[Math.PI, -0.93, Math.PI]} scale={0.57}>
                <group name="GLTF_created_37">
                  <primitive object={nodes.GLTF_created_37_rootJoint} />
                  <skinnedMesh name="Object_631" geometry={nodes.Object_631.geometry} material={materials.SeaWeed_1} skeleton={nodes.Object_631.skeleton} />
                </group>
              </group>
              <group name="Plank_1_487" position={[4.65, 15.08, 2.16]} scale={0.2}>
                <mesh name="Object_645" geometry={nodes.Object_645.geometry} material={materials.Wood_4} />
              </group>
              <group name="Plank_2_488" position={[4.17, 15.08, 1.03]} scale={0.2}>
                <mesh name="Object_647" geometry={nodes.Object_647.geometry} material={materials.Wood_3} />
              </group>
              <group name="Plank_Smal_1_489" position={[4.62, 15.08, 0.29]} scale={0.2}>
                <mesh name="Object_649" geometry={nodes.Object_649.geometry} material={materials.Wood_1} />
              </group>
              <group name="Plank_Smal_2_490" position={[4.18, 15.08, 2.81]} rotation={[-Math.PI, 0, 0]} scale={0.2}>
                <mesh name="Object_651" geometry={nodes.Object_651.geometry} material={materials.Wood_1} />
              </group>
              <group name="Plank_3_491" position={[3.72, 15.08, 2.27]} rotation={[-Math.PI, 0, -Math.PI]} scale={0.2}>
                <mesh name="Object_653" geometry={nodes.Object_653.geometry} material={materials.Wood_1} />
              </group>
              <group name="Plank_Smal_3_492" position={[3.73, 15.08, 0.35]} rotation={[0, 0, Math.PI]} scale={0.2}>
                <mesh name="Object_655" geometry={nodes.Object_655.geometry} material={materials.Wood_4} />
              </group>
              <group name="Plank_2001_493" position={[3.25, 15.08, 1.07]} scale={0.2}>
                <mesh name="Object_657" geometry={nodes.Object_657.geometry} material={materials.Wood_1} />
              </group>
              <group name="Plank_Smal_2001_494" position={[3.26, 15.08, 2.86]} rotation={[-Math.PI, 0, 0]} scale={0.2}>
                <mesh name="Object_659" geometry={nodes.Object_659.geometry} material={materials.Wood_1} />
              </group>
              <group name="Plank_1001_495" position={[2.8, 15.08, 2.22]} scale={0.2}>
                <mesh name="Object_661" geometry={nodes.Object_661.geometry} material={materials.Wood_3} />
              </group>
              <group name="Plank_2002_496" position={[2.31, 15.08, 1.08]} scale={0.2}>
                <mesh name="Object_663" geometry={nodes.Object_663.geometry} material={materials.Wood_1} />
              </group>
              <group name="Plank_Smal_2002_497" position={[2.32, 15.08, 2.87]} rotation={[-Math.PI, 0, 0]} scale={0.2}>
                <mesh name="Object_665" geometry={nodes.Object_665.geometry} material={materials.Wood_4} />
              </group>
              <group name="Plank_3001_498" position={[1.87, 15.08, 2.33]} rotation={[-Math.PI, 0, -Math.PI]} scale={0.2}>
                <mesh name="Object_667" geometry={nodes.Object_667.geometry} material={materials.Wood_1} />
              </group>
              <group name="Plank_Smal_3001_499" position={[1.88, 15.08, 0.41]} rotation={[0, 0, Math.PI]} scale={0.2}>
                <mesh name="Object_669" geometry={nodes.Object_669.geometry} material={materials.Wood_3} />
              </group>
              <group name="Plank_2003_500" position={[1.4, 15.08, 1.13]} scale={0.2}>
                <mesh name="Object_671" geometry={nodes.Object_671.geometry} material={materials.Wood_3} />
              </group>
              <group name="Plank_Smal_2003_501" position={[1.41, 15.08, 2.91]} rotation={[-Math.PI, 0, 0]} scale={0.2}>
                <mesh name="Object_673" geometry={nodes.Object_673.geometry} material={materials.Wood_4} />
              </group>
              <group name="Plank_Smal_1001_502" position={[2.77, 15.08, 0.35]} scale={0.2}>
                <mesh name="Object_675" geometry={nodes.Object_675.geometry} material={materials.Wood_1} />
              </group>
              <group name="Cube023_503" position={[-1.12, 9.45, 5.41]} rotation={[-0.41, -0.47, 0.07]}>
                <mesh name="Object_677" geometry={nodes.Object_677.geometry} material={materials.Wood_Dark} />
                <mesh name="Object_678" geometry={nodes.Object_678.geometry} material={materials.Chest_Metal} />
              </group>
              <group name="Plane028_504" position={[0.96, 11.69, 5.81]} rotation={[Math.PI / 2, 0, 0.4]} scale={5.03}>
                <mesh name="Object_680" geometry={nodes.Object_680.geometry} material={materials.Hook} />
              </group>
              <group name="Plank_1002_505" position={[2.84, 17.86, 2.34]} scale={0.2}>
                <mesh name="Object_682" geometry={nodes.Object_682.geometry} material={materials.Wood_3} />
              </group>
              <group name="Plank_2004_506" position={[2.36, 17.86, 1.2]} scale={0.2}>
                <mesh name="Object_684" geometry={nodes.Object_684.geometry} material={materials.Wood_1} />
              </group>
              <group name="Plank_Smal_1002_507" position={[2.81, 17.86, 0.47]} scale={0.2}>
                <mesh name="Object_686" geometry={nodes.Object_686.geometry} material={materials.Wood_1} />
              </group>
              <group name="Plank_Smal_2004_508" position={[2.37, 17.86, 2.99]} rotation={[-Math.PI, 0, 0]} scale={0.2}>
                <mesh name="Object_688" geometry={nodes.Object_688.geometry} material={materials.Wood_1} />
              </group>
              <group name="Plank_3002_509" position={[1.91, 17.86, 2.45]} rotation={[-Math.PI, 0, -Math.PI]} scale={0.2}>
                <mesh name="Object_690" geometry={nodes.Object_690.geometry} material={materials.Wood_1} />
              </group>
              <group name="Plank_Smal_3002_510" position={[1.92, 17.86, 0.53]} rotation={[0, 0, Math.PI]} scale={0.2}>
                <mesh name="Object_692" geometry={nodes.Object_692.geometry} material={materials.Wood_3} />
              </group>
              <group name="Plank_2005_511" position={[1.44, 17.86, 1.25]} scale={0.2}>
                <mesh name="Object_694" geometry={nodes.Object_694.geometry} material={materials.Wood_1} />
              </group>
              <group name="Plank_Smal_2005_512" position={[1.45, 17.86, 3.04]} rotation={[-Math.PI, 0, 0]} scale={0.2}>
                <mesh name="Object_696" geometry={nodes.Object_696.geometry} material={materials.Wood_3} />
              </group>
              <group name="Plank_3003_513" position={[3.76, 17.86, 2.39]} rotation={[-Math.PI, 0, -Math.PI]} scale={0.2}>
                <mesh name="Object_698" geometry={nodes.Object_698.geometry} material={materials.Wood_1} />
              </group>
              <group name="Plank_2006_514" position={[4.86, 17.86, 0.56]} rotation={[0, -Math.PI / 2, 0]} scale={0.2}>
                <mesh name="Object_700" geometry={nodes.Object_700.geometry} material={materials.Wood_3} />
              </group>
              <group name="Plank_Smal_2006_515" position={[3.3, 17.86, 2.98]} rotation={[-Math.PI, 0, 0]} scale={0.2}>
                <mesh name="Object_702" geometry={nodes.Object_702.geometry} material={materials.Wood_1} />
              </group>
              <group name="Plank_2007_516" position={[0.99, 17.86, 1.81]} scale={0.2}>
                <mesh name="Object_704" geometry={nodes.Object_704.geometry} material={materials.Wood_1} />
              </group>
              <group name="Plank_1003_517" position={[4.83, 17.86, 1.01]} rotation={[0, 1.55, 0]} scale={0.2}>
                <mesh name="Object_706" geometry={nodes.Object_706.geometry} material={materials.Wood_1} />
              </group>
              <group name="Plank_Smal_1003_518" position={[3.25, 17.86, 1.85]} scale={0.2}>
                <mesh name="Object_708" geometry={nodes.Object_708.geometry} material={materials.Wood_1} />
              </group>
              <group name="Plank_2008_519" position={[4.4, 17.86, 0.17]} rotation={[0, Math.PI / 2, 0]} scale={0.2}>
                <mesh name="Object_710" geometry={nodes.Object_710.geometry} material={materials.Wood_1} />
              </group>
              <group name="Plank_Smal_2008_520" position={[4.27, 17.95, 1.66]} rotation={[0, -0.58, 0]} scale={0.2}>
                <mesh name="Object_712" geometry={nodes.Object_712.geometry} material={materials.Wood_4} />
              </group>
              <group name="Plank_Smal_2014_521" position={[3.94, 17.93, 1.32]} rotation={[-Math.PI, 0.57, 0]} scale={0.2}>
                <mesh name="Object_714" geometry={nodes.Object_714.geometry} material={materials.Wood_3} />
              </group>
              <group name="Sand_522" position={[2.7, 9.44, 1.5]} scale={0.2}>
                <mesh name="Object_716" geometry={nodes.Object_716.geometry} material={materials.Sand} />
              </group>
              <group name="BigRock_523" position={[2.7, 11.38, 1.5]} scale={0.2}>
                <mesh name="Object_718" geometry={nodes.Object_718.geometry} material={materials.Rock_1} />
              </group>
              <group name="Rocks001_524" position={[-1.16, 9.51, 9.27]} scale={0.2}>
                <mesh name="Object_720" geometry={nodes.Object_720.geometry} material={materials.Rock_2} />
              </group>
              <group name="Rock002_525" position={[1.47, 9.05, 6.53]} rotation={[2.18, 0.34, 0.17]} scale={0.25}>
                <mesh name="Object_722" geometry={nodes.Object_722.geometry} material={materials.Rock_3} />
              </group>
              <group name="Rock003_526" position={[2.84, 9.28, 7.34]} rotation={[2.2, -0.63, -0.76]} scale={0.12}>
                <mesh name="Object_724" geometry={nodes.Object_724.geometry} material={materials.Rock_2} />
              </group>
              <group name="Rock004_527" position={[2.75, 9.05, 8.23]} rotation={[0.89, -0.05, 2.93]} scale={0.18}>
                <mesh name="Object_726" geometry={nodes.Object_726.geometry} material={materials.Rock_3} />
              </group>
              <group name="Rock005_528" position={[-3.38, 8.94, 5.37]} rotation={[-Math.PI, -0.45, -Math.PI]} scale={0.34}>
                <mesh name="Object_728" geometry={nodes.Object_728.geometry} material={materials.Rock_2} />
              </group>
              <group name="Rock006_529" position={[-2.84, 8.94, -4.42]} rotation={[0, 1.53, 0]} scale={0.25}>
                <mesh name="Object_730" geometry={nodes.Object_730.geometry} material={materials.Rock_2} />
              </group>
              <group name="Rock007_530" position={[7.58, 9.8, -3.95]} rotation={[1.99, -0.97, -2.02]} scale={0.25}>
                <mesh name="Object_732" geometry={nodes.Object_732.geometry} material={materials.Rock_2} />
              </group>
              <group name="Rock008_531" position={[7.88, 9.84, -5.16]} rotation={[-2.6, 0.18, 2.62]} scale={0.15}>
                <mesh name="Object_734" geometry={nodes.Object_734.geometry} material={materials.Rock_1} />
              </group>
              <group name="Rock009_532" position={[10.09, 9.72, -4.62]} rotation={[2.84, 0.31, 0.09]} scale={0.17}>
                <mesh name="Object_736" geometry={nodes.Object_736.geometry} material={materials.Rock_3} />
              </group>
              <group name="Rock010_533" position={[8.4, 9.72, 2.7]} rotation={[2.16, 1.08, 0.96]} scale={0.17}>
                <mesh name="Object_738" geometry={nodes.Object_738.geometry} material={materials.Rock_3} />
              </group>
              <group name="Rock011_534" position={[10.05, 9.55, 8.78]} rotation={[0.13, -0.16, 3.11]} scale={0.26}>
                <mesh name="Object_740" geometry={nodes.Object_740.geometry} material={materials.Rock_3} />
              </group>
              <group name="Rock012_535" position={[8.37, 9.81, -2.3]} rotation={[1.35, 1.1, 1.75]} scale={0.14}>
                <mesh name="Object_742" geometry={nodes.Object_742.geometry} material={materials.Rock_3} />
              </group>
              <group name="Rock013_536" position={[7.15, 9.75, -2.9]} rotation={[0.53, -0.98, -2.7]} scale={0.09}>
                <mesh name="Object_744" geometry={nodes.Object_744.geometry} material={materials.Rock_3} />
              </group>
              <group name="Plane001_540" position={[2.45, 20.15, 2.42]}>
                <mesh name="Object_746" geometry={nodes.Object_746.geometry} material={materials.Shade_1} />
                <mesh name="Object_747" geometry={nodes.Object_747.geometry} material={materials.Shade_2} />
              </group>
              <group name="rope1_541" position={[1.55, 20.19, 2.89]} rotation={[0.11, 0.15, 0.16]}>
                <mesh name="Object_749" geometry={nodes.Object_749.geometry} material={materials.Rope} />
              </group>
              <group name="rope2_542" position={[3.27, 20.14, 2.88]} rotation={[0.16, 0.15, -0.09]}>
                <mesh name="Object_751" geometry={nodes.Object_751.geometry} material={materials.Rope} />
              </group>
              <group name="Cylinder010_543" position={[1.73, 15.12, 2.57]}>
                <mesh name="Object_753" geometry={nodes.Object_753.geometry} material={materials.material} />
                <mesh name="Object_754" geometry={nodes.Object_754.geometry} material={materials.Pot_Bands} />
                <mesh name="Object_755" geometry={nodes.Object_755.geometry} material={materials.Pot_Dirt} />
              </group>
              <group name="Cylinder011_544" position={[1.71, 15.57, 2.55]}>
                <mesh name="Object_757" geometry={nodes.Object_757.geometry} material={materials.Palm_Ring} />
                <mesh name="Object_758" geometry={nodes.Object_758.geometry} material={materials.Palm} />
              </group>
              <group name="Plane002_545" position={[0.75, 17.15, 2.97]} scale={0.84}>
                <mesh name="Object_760" geometry={nodes.Object_760.geometry} material={materials.Leaf_1} />
              </group>
              <group name="Plane003_546" position={[0.75, 17.15, 2.97]} rotation={[0, 0.85, 0]} scale={0.77}>
                <mesh name="Object_762" geometry={nodes.Object_762.geometry} material={materials.Leaf_2} />
              </group>
              <group name="Plane004_547" position={[0.75, 17.15, 2.97]} rotation={[1.48, 1.48, -1.34]} scale={0.76}>
                <mesh name="Object_764" geometry={nodes.Object_764.geometry} material={materials.Leaf_1} />
              </group>
              <group name="Plane005_548" position={[0.75, 17.15, 2.97]} rotation={[-3.09, 0.66, -3.01]} scale={0.77}>
                <mesh name="Object_766" geometry={nodes.Object_766.geometry} material={materials.Leaf_3} />
              </group>
              <group name="Plane006_549" position={[0.75, 17.15, 2.97]} rotation={[3.04, -0.14, -3.11]} scale={0.84}>
                <mesh name="Object_768" geometry={nodes.Object_768.geometry} material={materials.Leaf_2} />
              </group>
              <group name="Plane007_550" position={[0.75, 17.15, 2.97]} rotation={[3.08, -1, -3.09]} scale={0.77}>
                <mesh name="Object_770" geometry={nodes.Object_770.geometry} material={materials.Leaf_3} />
              </group>
              <group name="Plane008_551" position={[0.75, 17.15, 2.97]} rotation={[0.36, -1.42, 0.6]} scale={0.76}>
                <mesh name="Object_772" geometry={nodes.Object_772.geometry} material={materials.Leaf_2} />
              </group>
              <group name="Plane009_552" position={[0.75, 17.15, 2.97]} rotation={[-0.2, -0.45, 0.1]} scale={0.77}>
                <mesh name="Object_774" geometry={nodes.Object_774.geometry} material={materials.Leaf_3} />
              </group>
              <group name="Plane010_553" position={[0.76, 17.18, 2.97]} rotation={[-2.94, -0.32, -3.07]} scale={0.8}>
                <mesh name="Object_776" geometry={nodes.Object_776.geometry} material={materials.Leaf_1} />
              </group>
              <group name="Plane011_554" position={[0.74, 17.16, 2.96]} rotation={[-2.81, -1.17, -2.98]} scale={1.02}>
                <mesh name="Object_778" geometry={nodes.Object_778.geometry} material={materials.Leaf_2} />
              </group>
              <group name="Plane012_555" position={[0.74, 17.17, 2.96]} rotation={[0.29, -1.26, 0.23]} scale={1.01}>
                <mesh name="Object_780" geometry={nodes.Object_780.geometry} material={materials.Leaf_1} />
              </group>
              <group name="Plane013_556" position={[0.74, 17.16, 2.97]} rotation={[0.26, -0.58, 0.2]} scale={1.02}>
                <mesh name="Object_782" geometry={nodes.Object_782.geometry} material={materials.Leaf_2} />
              </group>
              <group name="Cylinder012_557" position={[0.75, 17.15, 2.97]} rotation={[0.04, 0, 0.01]}>
                <mesh name="Object_784" geometry={nodes.Object_784.geometry} material={materials.Palm_Top} />
              </group>
              <group name="Vert_558" position={[5.04, 18.86, 1.65]}>
                <mesh name="Object_786" geometry={nodes.Object_786.geometry} material={materials.Rope} />
              </group>
              <group name="Cylinder014_559" position={[4.99, 18.86, 1.61]}>
                <mesh name="Object_788" geometry={nodes.Object_788.geometry} material={materials.Rope} />
              </group>
              <group name="Cylinder015_560" position={[4.98, 21.83, 1.73]}>
                <mesh name="Object_790" geometry={nodes.Object_790.geometry} material={materials.Rope} />
              </group>
              <group name="Cylinder016_561" position={[4.98, 22.38, 1.74]}>
                <mesh name="Object_792" geometry={nodes.Object_792.geometry} material={materials.Rope} />
              </group>
              <group name="Rock001_563" position={[-2.9, 9.82, -2.92]} rotation={[-0.06, 0.1, 2.63]} scale={0.12}>
                <mesh name="Object_794" geometry={nodes.Object_794.geometry} material={materials.Rock_2} />
              </group>
              <group name="Cube_564" position={[3.02, 14.89, 3.2]} scale={0.2}>
                <mesh name="Object_796" geometry={nodes.Object_796.geometry} material={materials.Wood_Dark} />
              </group>
              <group name="Cube001_565" position={[1.21, 14.86, 0.06]} scale={0.2}>
                <mesh name="Object_798" geometry={nodes.Object_798.geometry} material={materials.Wood_Dark} />
              </group>
              <group name="Cube002_566" position={[1.19, 14.86, 0.97]} scale={0.2}>
                <mesh name="Object_800" geometry={nodes.Object_800.geometry} material={materials.Wood_Dark} />
              </group>
              <group name="Cube003_567" position={[4.85, 14.87, 2.15]} rotation={[0, 0, Math.PI]} scale={0.2}>
                <mesh name="Object_802" geometry={nodes.Object_802.geometry} material={materials.Wood_Dark} />
              </group>
              <group name="Cylinder_568" position={[1.12, 15.07, 3.56]} scale={0.2}>
                <mesh name="Object_804" geometry={nodes.Object_804.geometry} material={materials.Wood_Dark} />
              </group>
              <group name="Cylinder001_569" position={[5.06, 15.06, 3.52]} scale={0.2}>
                <mesh name="Object_806" geometry={nodes.Object_806.geometry} material={materials.Wood_Dark} />
              </group>
              <group name="Cylinder002_570" position={[5.02, 15.07, 1.28]} scale={0.2}>
                <mesh name="Object_808" geometry={nodes.Object_808.geometry} material={materials.Wood_Dark} />
              </group>
              <group name="Cube004_571" position={[4.75, 14.61, 1.66]} rotation={[-Math.PI / 2, 0, -Math.PI / 2]} scale={0.2}>
                <mesh name="Object_810" geometry={nodes.Object_810.geometry} material={materials.Wood_Dark} />
              </group>
              <group name="Cube005_572" position={[1.38, 14.58, 1.66]} rotation={[-Math.PI / 2, 0, Math.PI / 2]} scale={0.2}>
                <mesh name="Object_812" geometry={nodes.Object_812.geometry} material={materials.Wood_Dark} />
              </group>
              <group name="Cylinder003_573" position={[1.09, 15.07, 0.45]} rotation={[-Math.PI, -0.17, -Math.PI]} scale={0.2}>
                <mesh name="Object_814" geometry={nodes.Object_814.geometry} material={materials.Wood_Dark} />
              </group>
              <group name="Cube006_574" position={[2.28, 17.7, 3.35]} rotation={[-Math.PI / 2, 0, 0]} scale={0.16}>
                <mesh name="Object_816" geometry={nodes.Object_816.geometry} material={materials.Wood_Dark} />
              </group>
              <group name="Cube007_575" position={[1.94, 17.28, 3.46]} rotation={[-1.44, -0.51, -2.91]} scale={[0.08, 0.13, 0.13]}>
                <mesh name="Object_818" geometry={nodes.Object_818.geometry} material={materials.Wood_Dark} />
              </group>
              <group name="Cube008_576" position={[1.43, 17.45, 0.25]} rotation={[Math.PI, Math.PI / 2, 0]} scale={0.2}>
                <mesh name="Object_820" geometry={nodes.Object_820.geometry} material={materials.Wood_Dark} />
              </group>
              <group name="Cube009_577" position={[2.91, 17.69, 0.67]} scale={[0.23, 0.16, 0.16]}>
                <mesh name="Object_822" geometry={nodes.Object_822.geometry} material={materials.Wood_Dark} />
              </group>
              <group name="Cube010_578" position={[5.21, 17.68, 1.57]} rotation={[-Math.PI, -Math.PI / 2, 0]} scale={0.15}>
                <mesh name="Object_824" geometry={nodes.Object_824.geometry} material={materials.Wood_Dark} />
              </group>
              <group name="Cube011_579" position={[3.7, 17.7, 3.13]} rotation={[-Math.PI, 1.54, -Math.PI]} scale={0.15}>
                <mesh name="Object_826" geometry={nodes.Object_826.geometry} material={materials.Wood_Dark} />
              </group>
              <group name="Cube012_580" position={[3.28, 15.1, 1.89]} scale={0.2}>
                <mesh name="Object_828" geometry={nodes.Object_828.geometry} material={materials.Wood_3} />
              </group>
              <group name="Cube013_581" position={[5.21, 17.71, 0.47]} rotation={[-Math.PI, -Math.PI / 2, 0]} scale={0.15}>
                <mesh name="Object_830" geometry={nodes.Object_830.geometry} material={materials.Wood_Dark} />
              </group>
              <group name="Cube014_582" position={[3.24, 17.71, 0.51]} rotation={[-Math.PI, -Math.PI / 2, 0]} scale={0.15}>
                <mesh name="Object_832" geometry={nodes.Object_832.geometry} material={materials.Wood_Dark} />
              </group>
              <group name="Cube015_583" position={[2.33, 21.12, 1.06]} rotation={[0, 0, -0.6]} scale={0.2}>
                <mesh name="Object_834" geometry={nodes.Object_834.geometry} material={materials.Roof} />
              </group>
              <group name="Cube016_584" position={[1.34, 15.1, 1.88]} rotation={[-Math.PI, 0, -Math.PI]} scale={0.2}>
                <mesh name="Object_836" geometry={nodes.Object_836.geometry} material={materials.Wood_3} />
              </group>
              <group name="Cube019_585" position={[2.38, 17.69, 1.89]} rotation={[Math.PI, 0, 0]} scale={0.15}>
                <mesh name="Object_838" geometry={nodes.Object_838.geometry} material={materials.Wood_3} />
              </group>
              <group name="Cube018_586" position={[1.34, 15.1, 0.24]} rotation={[-Math.PI, 0, -Math.PI]} scale={0.2}>
                <mesh name="Object_840" geometry={nodes.Object_840.geometry} material={materials.Wood_3} />
              </group>
              <group name="Cube017_587" position={[3.28, 15.1, 0.25]} scale={0.2}>
                <mesh name="Object_842" geometry={nodes.Object_842.geometry} material={materials.Wood_3} />
              </group>
              <group name="Cylinder004_588" position={[4.98, 14.89, 3.67]} rotation={[0, 0, -Math.PI / 2]} scale={0.2}>
                <mesh name="Object_844" geometry={nodes.Object_844.geometry} material={materials.Wood_4} />
              </group>
              <group name="Cylinder005_589" position={[5.01, 14.45, 3.68]} rotation={[0, 0, -Math.PI / 2]} scale={0.2}>
                <mesh name="Object_846" geometry={nodes.Object_846.geometry} material={materials.Wood_4} />
              </group>
              <group name="Cylinder006_590" position={[5.04, 13.96, 3.69]} rotation={[2.01, 0, -Math.PI / 2]} scale={0.2}>
                <mesh name="Object_848" geometry={nodes.Object_848.geometry} material={materials.Wood_4} />
              </group>
              <group name="Cylinder007_591" position={[5.38, 13.69, 3.67]} rotation={[1.14, 0, Math.PI / 2]} scale={0.2}>
                <mesh name="Object_850" geometry={nodes.Object_850.geometry} material={materials.Wood_4} />
              </group>
              <group name="Cylinder008_592" position={[1.81, 17.91, 2.48]} rotation={[0.16, 0.06, 0.12]} scale={[0.06, 0.08, 0.06]}>
                <mesh name="Object_852" geometry={nodes.Object_852.geometry} material={materials.Wood_Dark} />
              </group>
              <group name="Cylinder009_593" position={[3, 17.9, 2.54]} rotation={[0.12, -0.14, -0.11]} scale={[0.04, 0.08, 0.04]}>
                <mesh name="Object_854" geometry={nodes.Object_854.geometry} material={materials.Wood_Dark} />
              </group>
              <group name="Cylinder013_594" position={[5.02, 16.53, 1.58]} rotation={[0.02, 0.02, 0]} scale={[0.06, 0.18, 0.06]}>
                <mesh name="Object_856" geometry={nodes.Object_856.geometry} material={materials.Wood_Dark} />
              </group>
              <group name="Cylinder017_595" position={[2.95, 17.4, 0.05]} rotation={[-Math.PI / 2, Math.PI / 2, 0]} scale={0.2}>
                <mesh name="Object_858" geometry={nodes.Object_858.geometry} material={materials.Wood_4} />
              </group>
              <group name="Plane014_597" position={[3.78, 17.41, -0.25]} rotation={[Math.PI / 2, 0, 0]} scale={1.96}>
                <mesh name="Object_860" geometry={nodes.Object_860.geometry} material={materials.Cloth_Red} />
              </group>
              <group name="Plane015_598" position={[4.15, 17.45, -0.25]} rotation={[1.57, 0.06, 0.01]} scale={0.91}>
                <mesh name="Object_862" geometry={nodes.Object_862.geometry} material={materials.Cloth_Blue} />
              </group>
              <group name="Cylinder018_599" position={[2.26, 17.92, 2.09]} rotation={[1.1, 0.89, 0.57]} scale={[0.03, 0.11, 0.03]}>
                <mesh name="Object_864" geometry={nodes.Object_864.geometry} material={materials.Wood_Dark} />
              </group>
              <group name="Cylinder020_601" position={[1.5, 18.36, 3.02]} rotation={[-0.23, -0.04, -0.05]}>
                <mesh name="Object_866" geometry={nodes.Object_866.geometry} material={materials.Wood_Dark} />
              </group>
              <group name="Cylinder024_602" position={[4.61, 15.1, 2.57]} rotation={[-0.26, 0.88, 0.33]} scale={[0.05, 0.11, 0.05]}>
                <mesh name="Object_868" geometry={nodes.Object_868.geometry} material={materials.Wood_Dark} />
              </group>
              <group name="Cylinder023_603" position={[2.84, 20.74, 0.9]}>
                <mesh name="Object_870" geometry={nodes.Object_870.geometry} material={materials.Metal_1} />
              </group>
              <group name="Torus001_604" position={[3.45, 19.47, 1.05]} rotation={[0, 0, -Math.PI / 2]}>
                <mesh name="Object_872" geometry={nodes.Object_872.geometry} material={materials.Saver_white} />
                <mesh name="Object_873" geometry={nodes.Object_873.geometry} material={materials.Saver_Red} />
              </group>
              <group name="Cylinder025_605" position={[3.39, 19.75, 1.05]} rotation={[0.11, 0.02, -1.35]} scale={0.11}>
                <mesh name="Object_875" geometry={nodes.Object_875.geometry} material={materials.Wood_4} />
              </group>
              <group name="Cube020_606" position={[6.09, 17.82, 0.65]}>
                <mesh name="Object_877" geometry={nodes.Object_877.geometry} material={materials.Rope} />
                <mesh name="Object_878" geometry={nodes.Object_878.geometry} material={materials.Metal_1} />
                <mesh name="Object_879" geometry={nodes.Object_879.geometry} material={materials.Lamp_Light} />
              </group>
              <group name="Cylinder027_607" position={[3.83, 15.13, 0.49]}>
                <mesh name="Object_881" geometry={nodes.Object_881.geometry} material={materials.Barrel} />
                <mesh name="Object_882" geometry={nodes.Object_882.geometry} material={materials.Metal_1} />
              </group>
              <group name="Cylinder028_608" position={[5.23, 18.99, 0.61]} rotation={[0, -0.32, -1.16]}>
                <mesh name="Object_884" geometry={nodes.Object_884.geometry} material={materials.Telescope_Brass} />
                <mesh name="Object_885" geometry={nodes.Object_885.geometry} material={materials.Telescope_Lens} />
                <mesh name="Object_886" geometry={nodes.Object_886.geometry} material={materials.Telescope_Shaft} />
              </group>
              <group name="Cylinder029_609" position={[5.2, 18.94, 0.58]}>
                <mesh name="Object_888" geometry={nodes.Object_888.geometry} material={materials.Wood_Dark} />
                <mesh name="Object_889" geometry={nodes.Object_889.geometry} material={materials.Telescope_Brass} />
              </group>
              <group name="Cylinder019_612" position={[1.85, 15.54, 1.09]} rotation={[-0.23, -0.04, -0.05]}>
                <mesh name="Object_891" geometry={nodes.Object_891.geometry} material={materials.Wood_Dark} />
              </group>
              <group name="Plane020_613" position={[8.95, 9.67, -4.47]} rotation={[-Math.PI, 0.75, -Math.PI]} scale={1.65}>
                <mesh name="Object_893" geometry={nodes.Object_893.geometry} material={materials.SeaWeed_1} />
              </group>
              <group name="Cylinder047_614" position={[-1.07, 10.53, 8.85]}>
                <mesh name="Object_895" geometry={nodes.Object_895.geometry} material={materials.StarFish} />
              </group>
              <group name="Cylinder048_615" position={[7.89, 13.56, 5.45]} rotation={[-0.16, -0.06, -0.17]}>
                <mesh name="Object_897" geometry={nodes.Object_897.geometry} material={materials.StarFish} />
              </group>
              <group name="Dry_line001_616" position={[2.95, 17.46, -0.44]}>
                <mesh name="Object_899" geometry={nodes.Object_899.geometry} material={materials.Rope} />
              </group>
              <group name="Fisshing_line001_617" position={[1.32, 17.96, 4.7]} rotation={[-Math.PI / 2, 0, -1.91]}>
                <mesh name="Object_901" geometry={nodes.Object_901.geometry} material={materials.Fishing_Line} />
              </group>
              <group name="NurbsCurve002_618" position={[4.97, 18.62, 1.4]}>
                <mesh name="Object_903" geometry={nodes.Object_903.geometry} material={materials.Rope} />
              </group>
              <group name="NurbsCurve003_619" position={[5.01, 17.68, 1.4]}>
                <mesh name="Object_905" geometry={nodes.Object_905.geometry} material={materials.Rope} />
              </group>
              <group name="Plank_3011_620" position={[1.63, 16.39, 1.96]} rotation={[Math.PI / 2, 0, Math.PI]} scale={0.2}>
                <mesh name="Object_907" geometry={nodes.Object_907.geometry} material={materials.Wood_1} />
              </group>
              <group name="Plank_3012_621" position={[2.98, 16.22, 1.96]} rotation={[-Math.PI / 2, 0, 0]} scale={0.2}>
                <mesh name="Object_909" geometry={nodes.Object_909.geometry} material={materials.Wood_3} />
              </group>
              <group name="Plank_2014_622" position={[2.2, 17.38, 1.98]} rotation={[Math.PI / 2, -Math.PI / 2, 0]} scale={0.2}>
                <mesh name="Object_911" geometry={nodes.Object_911.geometry} material={materials.Wood_1} />
              </group>
              <group name="Plank_3013_623" position={[3.35, 16.3, 1.6]} rotation={[Math.PI / 2, 0, -Math.PI / 2]} scale={0.2}>
                <mesh name="Object_913" geometry={nodes.Object_913.geometry} material={materials.Wood_2} />
              </group>
              <group name="Plank_Smal_2015_624" position={[3.34, 15.64, 1.24]} rotation={[-Math.PI / 2, 0, -Math.PI / 2]} scale={0.2}>
                <mesh name="Object_915" geometry={nodes.Object_915.geometry} material={materials.Wood_1} />
              </group>
              <group name="Plank_Smal_3003_625" position={[3.34, 15.88, 0.9]} rotation={[Math.PI / 2, 0, Math.PI / 2]} scale={0.2}>
                <mesh name="Object_917" geometry={nodes.Object_917.geometry} material={materials.Wood_2} />
              </group>
              <group name="Plank_3014_626" position={[3.35, 16.3, 0.55]} rotation={[-1.57, 0, Math.PI / 2]} scale={0.2}>
                <mesh name="Object_919" geometry={nodes.Object_919.geometry} material={materials.Wood_1} />
              </group>
              <group name="Plank_Smal_2016_627" position={[3.34, 17.46, 0.93]} rotation={[Math.PI / 2, 0, -Math.PI / 2]} scale={0.2}>
                <mesh name="Object_921" geometry={nodes.Object_921.geometry} material={materials.Wood_1} />
              </group>
              <group name="Plank_Smal_3004_628" position={[3.34, 17.22, 1.27]} rotation={[-Math.PI / 2, 0, Math.PI / 2]} scale={0.2}>
                <mesh name="Object_923" geometry={nodes.Object_923.geometry} material={materials.Wood_1} />
              </group>
              <group name="Plank_3015_629" position={[2.94, 16.22, 0.18]} rotation={[-Math.PI / 2, 0, -Math.PI]} scale={0.2}>
                <mesh name="Object_925" geometry={nodes.Object_925.geometry} material={materials.Wood_2} />
              </group>
              <group name="Plank_3016_630" position={[2.52, 15.57, 0.2]} rotation={[Math.PI / 2, 0, Math.PI]} scale={0.2}>
                <mesh name="Object_927" geometry={nodes.Object_927.geometry} material={materials.Wood_1} />
              </group>
              <group name="Plank_2015_631" position={[2.08, 15.52, 0.2]} rotation={[Math.PI / 2, 0, 0]} scale={0.2}>
                <mesh name="Object_929" geometry={nodes.Object_929.geometry} material={materials.Wood_1} />
              </group>
              <group name="Plank_3017_632" position={[1.67, 16.39, 0.22]} rotation={[Math.PI / 2, 0, Math.PI]} scale={0.2}>
                <mesh name="Object_931" geometry={nodes.Object_931.geometry} material={materials.Wood_2} />
              </group>
              <group name="Plank_3018_633" position={[1.28, 16.36, 1.61]} rotation={[Math.PI / 2, 0, -Math.PI / 2]} scale={0.2}>
                <mesh name="Object_933" geometry={nodes.Object_933.geometry} material={materials.Wood_2} />
              </group>
              <group name="Plank_2016_634" position={[1.29, 16.32, 1.31]} rotation={[Math.PI / 2, 0, -Math.PI / 2]} scale={0.2}>
                <mesh name="Object_935" geometry={nodes.Object_935.geometry} material={materials.Wood_1} />
              </group>
              <group name="Plank_2017_635" position={[1.29, 16.61, 0.97]} rotation={[-Math.PI / 2, 0, Math.PI / 2]} scale={0.2}>
                <mesh name="Object_937" geometry={nodes.Object_937.geometry} material={materials.Wood_2} />
              </group>
              <group name="Plank_3019_636" position={[1.28, 16.6, 0.61]} rotation={[-Math.PI / 2, 0, Math.PI / 2]} scale={0.2}>
                <mesh name="Object_939" geometry={nodes.Object_939.geometry} material={materials.Wood_1} />
              </group>
              <group name="Plank_3004_637" position={[2.08, 17.37, 0.2]} rotation={[-Math.PI / 2, 0, 0]} scale={0.2}>
                <mesh name="Object_941" geometry={nodes.Object_941.geometry} material={materials.Wood_1} />
              </group>
              <group name="Plank_2009_638" position={[2.52, 17.42, 0.2]} rotation={[-Math.PI / 2, 0, -3.14]} scale={0.2}>
                <mesh name="Object_943" geometry={nodes.Object_943.geometry} material={materials.Wood_1} />
              </group>
            </group>
          </group>
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/beach-transformed.glb')
