/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 elephant.gltf --transform
Author: denys4624 (https://sketchfab.com/denys4624)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/elephant-gajah-d53f4e537d07419caefabef2cd4bbf7b
Title: Elephant | Gajah
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Elephant(props) {
  const { nodes, materials } = useGLTF('/elephant-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <group position={[0, -78.01, 358.03]}>
          <group position={[0, 78.01, -358.03]}>
            <mesh geometry={nodes.Object_3.geometry} material={materials.ElphSkin} />
            <mesh geometry={nodes.Object_4.geometry} material={materials.ElphSkin} />
          </group>
          <group position={[-80.66, -326.83, 160.46]}>
            <mesh geometry={nodes.Object_7.geometry} material={materials.ElepEYE} position={[80.66, 404.84, -518.49]} />
          </group>
          <group position={[80.66, -326.83, 160.46]}>
            <mesh geometry={nodes.Object_10.geometry} material={materials.ElepEYE} position={[-80.66, 404.84, -518.49]} />
          </group>
          <group position={[-101.73, -490.68, 40.28]}>
            <mesh geometry={nodes.Object_13.geometry} material={materials.Ele_Tuskh} position={[101.73, 568.69, -398.32]} />
          </group>
          <group position={[101.73, -490.68, 40.28]}>
            <mesh geometry={nodes.Object_16.geometry} material={materials.Ele_Tuskh} position={[-101.73, 568.69, -398.32]} />
          </group>
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/elephant-transformed.glb')
