/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 newearth.gltf --transform
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function NewEarth(props) {
  const { nodes, materials } = useGLTF('/newearth-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Sphere001.geometry} material={materials['Material.002']} />
    </group>
  )
}

useGLTF.preload('/newearth-transformed.glb')
