/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 piggy_bank.gltf --transform
Author: mistour (https://sketchfab.com/mistour)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/piggy-bank-d4387ba82d8f4dda85826ee5815640b9
Title: Piggy Bank
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Piggy(props) {
  const { nodes, materials } = useGLTF('/piggy_bank-transformed.glb')
  return (
      <group {...props} dispose={null} >
      <mesh geometry={nodes.Object_4.geometry} material={materials.Material} />
      <mesh geometry={nodes.Object_5.geometry} material={materials['Material.001']} />
    </group>
  )
}

useGLTF.preload('/piggy_bank-transformed.glb')
